spring:
  datasource:
    url: jdbc:mysql://47.104.148.255:3306/Demo?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 1000
      min-idle: 5
      initial-size: 5
  elasticsearch:
    jest:
      uris:
      - http://47.104.148.255:9300
      read-timeout: 5000    

server:
  port: 8080
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml
  
  
        
     
        